name: Publish PowerShell Module
on:
    push:
        tags:
          - '*'
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Test Module Manifest
      run: Test-ModuleManifest -Path .\AcuInstallerHelper\AcuInstallerHelper.psd1

    - name: Install Pester
      run: Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Import Built Module
      run: |
        $modulePath = Join-Path $PSScriptRoot ".\AcuInstallerHelper\" 
        Import-Module -Name $modulePath

    - name: Test
      run: Invoke-Pester -Path .\AcuInstallerHelper.Tests\AcuInstallerHelper.Tests.ps1

    - name: Publish to PowerShell Gallery
      env:
          NUGET_API_KEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
      run: |
          $version = ${{ github.ref }}
          Publish-Module -Path AcuInstallerHelper\ -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }} -Verbose
