name: Test PowerShell Module
on: workflow_dispatch
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Test Module Manifest
      run: Test-ModuleManifest -Path .\AcuInstallerHelper\AcuInstallerHelper.psd1

    - name: Install Pester
      run: Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Import Built Module
      run: |
        $modulePath = Join-Path $PSScriptRoot ".\AcuInstallerHelper\" 
        Import-Module -Name $modulePath

    - name: Test
      run: Invoke-Pester -Path .\AcuInstallerHelper.Tests\AcuInstallerHelper.Tests.ps1


